# Generated by Django 3.2.20 on 2025-05-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
