# Generated by Django 3.2.20 on 2025-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
    ]
