# Generated by Django 4.2.29 on 2026-03-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_enable_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'ip_address'], name='core_postli_post_id_2af8ed_idx'), models.Index(fields=['post', 'created_at'], name='core_postli_post_id_26ed63_idx')],
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
