# Generated by Django 4.2.29 on 2026-07-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.post')),
                ('endereco_completo', models.CharField(help_text='Ex: Av. Paulista, 900 - Bela Vista, São Paulo - SP, 01310-100', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(default='Brasil', max_length=100)),
            ],
            bases=('core.post',),
        ),
    ]
